import {useEffect, useState} from 'react';
import {Coins, LogOut, Minus, Plus, X} from 'lucide-react';
import {api} from './api.js';
import {BET_LIMITS} from './constants.js';
import {money} from './format.js';
import {Popup, usePopup} from './Popup.jsx';

export function AccountPanel({view,onClose,user,token,setUser,onLogout}){
 // Kết quả lưu hồ sơ và yêu cầu nạp/rút đều báo bằng popup.
 const notice=usePopup();
 const setMessage=text=>notice.show(text, /lỗi|không|thất bại/i.test(text)?'fail':'ok');
 const [items,setItems]=useState([]),[name,setName]=useState(user.displayName),[amount,setAmount]=useState(50000);
 useEffect(()=>{const path=view==='history'?'/transactions':view==='wallet'?'/wallet/requests':null;if(path)api(path,{token}).then(data=>setItems(data.items)).catch(err=>setMessage(err.message))},[view,token]);
 const save=async()=>{try{const data=await api('/me',{token,method:'PATCH',body:JSON.stringify({displayName:name})});setUser(data.user);setMessage('Đã lưu hồ sơ')}catch(err){setMessage(err.message)}};
 const wallet=async type=>{try{const data=await api(`/wallet/${type}`,{token,method:'POST',body:JSON.stringify({amount:Number(amount)})}),profile=await api('/me',{token});setUser(profile.user);setItems(current=>[data.request,...current]);setMessage(`Đã tạo yêu cầu #${data.request.id.slice(-6)}. Trạng thái: chờ xử lý.`)}catch(err){setMessage(err.message)}};
 return <div className="panelBackdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="accountPanel"><button className="panelClose" onClick={onClose}><X/></button>{view==='history'?<><h2>Lịch sử giao dịch</h2><p className="panelLead">100 giao dịch gần nhất</p><div className="transactionList">{items.length?items.map(item=><article key={item.id}><div><strong>{item.description}</strong><small>{new Date(item.createdAt).toLocaleString('vi-VN')}</small></div><span className={item.amount>=0?'positive':'negative'}>{item.amount>=0?'+':''}{money(item.amount)}</span></article>):<div className="emptyState">Chưa có giao dịch</div>}</div></>:view==='wallet'?<><h2>Ví GoldZone</h2><p className="walletBalance"><Coins/> {money(user.balance)}</p><label className="profileField">Số tiền<input type="number" min={BET_LIMITS.wallet.min} max={BET_LIMITS.wallet.max} step="50000" value={amount} onChange={e=>setAmount(e.target.value)}/></label><div className="walletActions"><button className="panelAction bonus" onClick={()=>wallet('deposit')}><Plus/> Yêu cầu nạp</button><button className="panelAction" onClick={()=>wallet('withdraw')}><Minus/> Yêu cầu rút</button></div><p className="walletNotice">Đây là hệ thống yêu cầu nội bộ; không tích hợp thanh toán tiền thật.</p><div className="requestList">{items.map(item=><article key={item.id}><span>{item.type==='DEPOSIT'?'NẠP':'RÚT'} {money(item.amount)}</span><b className={item.status.toLowerCase()}>{item.status==='PENDING'?'CHỜ DUYỆT':item.status==='APPROVED'?'ĐÃ DUYỆT':'TỪ CHỐI'}</b></article>)}</div></>:<><div className="profileHero"><img src="/assets/home-avatar.webp" alt="Ảnh đại diện" loading="eager" decoding="async"/><div><small>THÀNH VIÊN</small><h2>{user.displayName}</h2><p>@{user.username}</p></div></div><label className="profileField">Tên hiển thị<input value={name} onChange={e=>setName(e.target.value)}/></label><button className="panelAction" onClick={save}>Lưu thay đổi</button><button className="logoutBtn" onClick={onLogout}><LogOut/> Đăng xuất</button></>}<Popup popup={notice.popup} onClose={notice.close}/></section></div>;
}
